name: Build Godot Project

on:
  pull_request: {}

jobs:
  Godot-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Linux, Windows]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: krynv/build-godot-action@v1.0.0
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: Client-${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
