name: Build Godot Project

on:
  pull_request: {}

jobs:
  Godot-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Linux, Windows, Web]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: krynv/build-godot-action@v1.0.0
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
  webgl-export-to-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: Client - Web
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: Client - Web
          
