name: Labeller
  on:
    workflow_run:
      workflows: ["Build Godot Project"]
      types:
        - success

  jobs:
    label_pr:
      runs-on: ubuntu-latest
      steps:
        - env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}}
        run: |
          gh pr edit $PR --add-label 'needs review'


